version: '3'
services:
  annotation:
    build:
      context: ./annotation
    volumes:
      - ./shared:/app/shared
    ports:
      - "3001:3001"
  collecte:
    build:
      context: ./collecte
    volumes:
      - ./shared:/app/shared
  recommandation:
    build:
      context: ./analyse_recommandation
    volumes:
      - ./shared:/app/shared
    ports:
      - "8080:8080"

  notebook:
    image: jupyter/pyspark-notebook
    volumes:
      - ./notebook:/home/jovyan/
      - ./shared:/home/jovyan/shared

    ports:
      - "8888:8888"
    environment:
      - PYSPARK_SUBMIT_ARGS='--jars /home/jovyan/sqlite-jdbc.jar  pyspark-shell'
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=''
    command: start.sh jupyter lab --NotebookApp.token=''
  
  visualisation:
    build:
      context: ./visualisation
    volumes:
      - ./shared:/app/shared
      - ./visualisation_images:/app/visualisation_images
    ports:
      - "3002:3002"

